export enum EnvironmentVariable {
  DATABASE_URL = 'DATABASE_URL',
  PORT = 'PORT',
  SESSION_SECRET = 'SESSION_SECRET',
  SESSION_NAME = 'SESSION_NAME',
  CORS_METHOD = 'CORS_METHOD',
  CORS_REG_EXP = 'CORS_REG_EXP',
  CORS_URL = 'CORS_URL',
  REDIS_URL = 'REDIS_URL',
  GOOGLE_SERVICE_ACCOUNT = 'GOOGLE_SERVICE_ACCOUNT',
}
