export enum PermissionCodes {
  Admin = 'ADMIN',
  UsersRead = 'USER_R',
  AreaCreate = 'AREA_C',
  AreaUpdate = 'AREA_U',
  AreaDelete = 'AREA_D',
  RoleCreate = 'ROLE_C',
  RoleUpdate = 'ROLE_U',
  RoleDelete = 'ROLE_D',
  AdminRole = 'ADMIN_ROLE',
  AdminArea = 'ADMIN_AREA',
  RoleUserCreate = 'ROLEUSER_C',
  RoleUserDelete = 'ROLEUSER_D',
  PatientRead = 'PATIENT_R',
  PatientCreate = 'PATIENT_C',
  PatientUpdate = 'PATIENT_U',
  ProfessionalCreate = 'PROFESSIONAL_C',
  ProfessionalDelete = 'PROFESSIONAL_D',
  ProfessionalUpdate = 'PROFESSIONAL_U',
  ProfessionalRead = 'PROFESSIONAL_R',
  TreatmentCreate = 'TREATMENT_C',
  TreatmentUpdate = 'TREATMENT_U',
  TreatmentDelete = 'TREATMENT_D',
  TreatmentRead = 'TREATMENT_R',
  DocumentationRead = 'DOCUMENTATION_R',
  DocumentationCreate = 'DOCUMENTATION_C',
}
