version: '2.7'

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: arene
      MYSQL_USER: arene
      MYSQL_PASSWORD: example
    container_name: arene-db
    volumes:
      - ./mysqlData:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: 'bitnami/redis:latest'
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - 6379:6379
    volumes:
      - ./redisData:/bitnami/redis/data
    container_name: arene-redis